// Verity-owned ESLint config for the quality gate. Generated by `verity init`.
//
// Deliberately SEPARATE from the project's ./eslint.config.js. Pointing the gate at
// the project config makes Verity's pattern list a FILTER over rules the project
// enabled, so any rule the project disables becomes unreachable (VRT-108).
//
// The enabled rules come from .codacy/codacy.config.json; this file supplies only
// the parser, the globals and the ignores ESLint needs to run at all.
//
// SCOPE (PR #187 review): this config binds ONLY inside Verity's own gate runner.
// Codacy cloud/CLI analysis (codacy-analysis, configSource "codacy") does NOT read it —
// exclusions that must bind there live in the repo-root .codacy.yaml, which is where
// .claude/skills/** and .codacy/** are excluded from Codacy routing.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist/**", "build/**", "node_modules/**", "coverage/**", ".codacy/**"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx,js,jsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
  },
);
