#!/bin/sh
# make-git-guard-hooks.sh — write the heddle git guard's hook wrappers into a directory.
#
# Usage: make-git-guard-hooks.sh <out-hooks-dir> <engine.py> <guard-config.json>
#
# It only writes wrapper files into <out-hooks-dir>. It never edits any repository
# config; pointing a repository at the directory is a separate, explicit step:
#   git config --file <repo>/.git/config core.hooksPath <out-hooks-dir>
# Undo that step with:
#   git config --file <repo>/.git/config --unset core.hooksPath
#
# Guarded hooks run the engine, which checks and then runs the repository's own
# hook of the same name from <git-common-dir>/hooks (Git LFS, for example).
# Every other client-side hook gets a chain-only wrapper, so hooks that already
# exist in <git-common-dir>/hooks keep running once core.hooksPath is set.
set -eu

out="${1:?usage: make-git-guard-hooks.sh <out-hooks-dir> <engine.py> <guard-config.json>}"
engine="${2:?engine path required}"
config="${3:?config path required}"
python_bin="${HEDDLE_GIT_GUARD_PYTHON:-/usr/bin/python3}"

mkdir -p "$out"

guarded="pre-commit pre-merge-commit pre-push post-checkout post-commit post-merge"
chain_only="applypatch-msg pre-applypatch post-applypatch prepare-commit-msg commit-msg pre-rebase post-rewrite pre-auto-gc"

for hook in $guarded; do
  cat > "$out/$hook" <<EOF
#!/bin/sh
# heddle git guard wrapper (generated by make-git-guard-hooks.sh). Hook: $hook
HEDDLE_GIT_GUARD_CONFIG="$config"
HEDDLE_GIT_GUARD_WRAPPER_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
export HEDDLE_GIT_GUARD_CONFIG HEDDLE_GIT_GUARD_WRAPPER_DIR
exec "$python_bin" "$engine" $hook "\$@"
EOF
  chmod 0755 "$out/$hook"
done

for hook in $chain_only; do
  cat > "$out/$hook" <<EOF
#!/bin/sh
# heddle git guard chain-only wrapper (generated). Runs the repository's own $hook, if any.
h="\$(git rev-parse --git-common-dir)/hooks/$hook"
here="\$(cd "\$(dirname "\$0")" && pwd)"
if [ -x "\$h" ] && [ "\$(cd "\$(dirname "\$h")" && pwd)" != "\$here" ]; then
  exec "\$h" "\$@"
fi
exit 0
EOF
  chmod 0755 "$out/$hook"
done

echo "wrote $(ls "$out" | wc -l | tr -d ' ') hook wrappers to $out"
